export const EMPLOYEES_LOADED = "Employees/EMPLOYEES_LOADED";
export const EMPLOYEE_ADD = "Employees/EMPLOYEE_ADD";
export const EMPLOYEES_LOADING = "Employees/EMPLOYEES_LOADING";
export const EMPLOYEES_LOADING_ERROR = "Employees/EMPLOYEES_LOADING_ERROR";